
package fogetti.phish.storm.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWiabService", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWiabService {


    /**
     * 
     * @return
     *     returns fogetti.phish.storm.wsdl.ArrayOfstring
     */
    @WebMethod(operationName = "GetModels", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/GetModels")
    @WebResult(name = "GetModelsResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "GetModels", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetModels")
    @ResponseWrapper(localName = "GetModelsResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetModelsResponse")
    public ArrayOfstring getModels();

    /**
     * 
     * @return
     *     returns fogetti.phish.storm.wsdl.ArrayOfstring
     */
    @WebMethod(operationName = "GetModelsForWordBreaker", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/GetModelsForWordBreaker")
    @WebResult(name = "GetModelsForWordBreakerResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "GetModelsForWordBreaker", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetModelsForWordBreaker")
    @ResponseWrapper(localName = "GetModelsForWordBreakerResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetModelsForWordBreakerResponse")
    public ArrayOfstring getModelsForWordBreaker();

    /**
     * 
     * @return
     *     returns fogetti.phish.storm.wsdl.ArrayOfstring
     */
    @WebMethod(operationName = "GetModelsForPhraseBreaker", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/GetModelsForPhraseBreaker")
    @WebResult(name = "GetModelsForPhraseBreakerResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "GetModelsForPhraseBreaker", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetModelsForPhraseBreaker")
    @ResponseWrapper(localName = "GetModelsForPhraseBreakerResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetModelsForPhraseBreakerResponse")
    public ArrayOfstring getModelsForPhraseBreaker();

    /**
     * 
     * @param authorizationToken
     * @param modelUrn
     * @param phrase
     * @return
     *     returns java.lang.Float
     */
    @WebMethod(operationName = "GetProbability", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/GetProbability")
    @WebResult(name = "GetProbabilityResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "GetProbability", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetProbability")
    @ResponseWrapper(localName = "GetProbabilityResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetProbabilityResponse")
    public Float getProbability(
        @WebParam(name = "authorizationToken", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String authorizationToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String modelUrn,
        @WebParam(name = "phrase", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String phrase);

    /**
     * 
     * @param authorizationToken
     * @param modelUrn
     * @param phrases
     * @return
     *     returns fogetti.phish.storm.wsdl.ArrayOffloat
     */
    @WebMethod(operationName = "GetProbabilities", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/GetProbabilities")
    @WebResult(name = "GetProbabilitiesResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "GetProbabilities", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetProbabilities")
    @ResponseWrapper(localName = "GetProbabilitiesResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetProbabilitiesResponse")
    public ArrayOffloat getProbabilities(
        @WebParam(name = "authorizationToken", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String authorizationToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String modelUrn,
        @WebParam(name = "phrases", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        ArrayOfstring phrases);

    /**
     * 
     * @param authorizationToken
     * @param modelUrn
     * @param phrase
     * @return
     *     returns java.lang.Float
     */
    @WebMethod(operationName = "GetConditionalProbability", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/GetConditionalProbability")
    @WebResult(name = "GetConditionalProbabilityResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "GetConditionalProbability", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetConditionalProbability")
    @ResponseWrapper(localName = "GetConditionalProbabilityResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetConditionalProbabilityResponse")
    public Float getConditionalProbability(
        @WebParam(name = "authorizationToken", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String authorizationToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String modelUrn,
        @WebParam(name = "phrase", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String phrase);

    /**
     * 
     * @param authorizationToken
     * @param modelUrn
     * @param phrases
     * @return
     *     returns fogetti.phish.storm.wsdl.ArrayOffloat
     */
    @WebMethod(operationName = "GetConditionalProbabilities", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/GetConditionalProbabilities")
    @WebResult(name = "GetConditionalProbabilitiesResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "GetConditionalProbabilities", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetConditionalProbabilities")
    @ResponseWrapper(localName = "GetConditionalProbabilitiesResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GetConditionalProbabilitiesResponse")
    public ArrayOffloat getConditionalProbabilities(
        @WebParam(name = "authorizationToken", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String authorizationToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String modelUrn,
        @WebParam(name = "phrases", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        ArrayOfstring phrases);

    /**
     * 
     * @param authorizationToken
     * @param modelUrn
     * @param cookie
     * @param maxN
     * @param phraseContext
     * @return
     *     returns fogetti.phish.storm.wsdl.TokenSet
     */
    @WebMethod(operationName = "Generate", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/Generate")
    @WebResult(name = "GenerateResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "Generate", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.Generate")
    @ResponseWrapper(localName = "GenerateResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.GenerateResponse")
    public TokenSet generate(
        @WebParam(name = "authorizationToken", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String authorizationToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String modelUrn,
        @WebParam(name = "phraseContext", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String phraseContext,
        @WebParam(name = "maxN", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        Integer maxN,
        @WebParam(name = "cookie", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String cookie);

    /**
     * 
     * @param authorizationToken
     * @param modelUrn
     * @param maxCandidates
     * @param text
     * @return
     *     returns fogetti.phish.storm.wsdl.WordBreakerResultSet
     */
    @WebMethod(operationName = "WordBreak", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/WordBreak")
    @WebResult(name = "WordBreakResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "WordBreak", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.WordBreak")
    @ResponseWrapper(localName = "WordBreakResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.WordBreakResponse")
    public WordBreakerResultSet wordBreak(
        @WebParam(name = "authorizationToken", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String authorizationToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String modelUrn,
        @WebParam(name = "text", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String text,
        @WebParam(name = "maxCandidates", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        Integer maxCandidates);

    /**
     * 
     * @param modelUrn
     * @param allowSinglePhrase
     * @param authToken
     * @param text
     * @param maxPhraseLength
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PhraseBreak", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/PhraseBreak")
    @WebResult(name = "PhraseBreakResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "PhraseBreak", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.PhraseBreak")
    @ResponseWrapper(localName = "PhraseBreakResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.PhraseBreakResponse")
    public String phraseBreak(
        @WebParam(name = "authToken", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String authToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String modelUrn,
        @WebParam(name = "text", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String text,
        @WebParam(name = "maxPhraseLength", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        Integer maxPhraseLength,
        @WebParam(name = "allowSinglePhrase", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        Boolean allowSinglePhrase);

    /**
     * 
     * @param modelUrn
     * @param authToken
     * @param text
     * @param maxPhraseLength
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PhraseBreakTree", action = "http://schemas.microsoft.com/research/2011/08/wiab/IWiabService/PhraseBreakTree")
    @WebResult(name = "PhraseBreakTreeResult", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
    @RequestWrapper(localName = "PhraseBreakTree", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.PhraseBreakTree")
    @ResponseWrapper(localName = "PhraseBreakTreeResponse", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab", className = "fogetti.phish.storm.wsdl.PhraseBreakTreeResponse")
    public String phraseBreakTree(
        @WebParam(name = "authToken", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String authToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String modelUrn,
        @WebParam(name = "text", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        String text,
        @WebParam(name = "maxPhraseLength", targetNamespace = "http://schemas.microsoft.com/research/2011/08/wiab")
        Integer maxPhraseLength);

}
