
package fogetti.phish.storm.wsdl.bing.webmaster;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWebmasterApi", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWebmasterApi {


    /**
     * 
     * @param siteUrl
     * @param blockedUrl
     * @throws IWebmasterApiAddBlockedUrlApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddBlockedUrl", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/AddBlockedUrl")
    @RequestWrapper(localName = "AddBlockedUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddBlockedUrl")
    @ResponseWrapper(localName = "AddBlockedUrlResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddBlockedUrlResponse")
    public void addBlockedUrl(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "blockedUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        BlockedUrl blockedUrl)
        throws IWebmasterApiAddBlockedUrlApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param settings
     * @param siteUrl
     * @throws IWebmasterApiAddCountryRegionSettingsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddCountryRegionSettings", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/AddCountryRegionSettings")
    @RequestWrapper(localName = "AddCountryRegionSettings", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddCountryRegionSettings")
    @ResponseWrapper(localName = "AddCountryRegionSettingsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddCountryRegionSettingsResponse")
    public void addCountryRegionSettings(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "settings", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        CountryRegionSettings settings)
        throws IWebmasterApiAddCountryRegionSettingsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param market
     * @param deepLinkUrl
     * @param siteUrl
     * @param searchUrl
     * @throws IWebmasterApiAddDeepLinkBlockApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddDeepLinkBlock", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/AddDeepLinkBlock")
    @RequestWrapper(localName = "AddDeepLinkBlock", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddDeepLinkBlock")
    @ResponseWrapper(localName = "AddDeepLinkBlockResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddDeepLinkBlockResponse")
    public void addDeepLinkBlock(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "market", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String market,
        @WebParam(name = "searchUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String searchUrl,
        @WebParam(name = "deepLinkUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String deepLinkUrl)
        throws IWebmasterApiAddDeepLinkBlockApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param disavowUrl
     * @param siteUrl
     * @param entityType
     * @throws IWebmasterApiAddDisavowedLinkApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddDisavowedLink", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/AddDisavowedLink")
    @RequestWrapper(localName = "AddDisavowedLink", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddDisavowedLink")
    @ResponseWrapper(localName = "AddDisavowedLinkResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddDisavowedLinkResponse")
    public void addDisavowedLink(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "disavowUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String disavowUrl,
        @WebParam(name = "entityType", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        Integer entityType)
        throws IWebmasterApiAddDisavowedLinkApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param queryParameter
     * @throws IWebmasterApiAddQueryParameterApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddQueryParameter", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/AddQueryParameter")
    @RequestWrapper(localName = "AddQueryParameter", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddQueryParameter")
    @ResponseWrapper(localName = "AddQueryParameterResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddQueryParameterResponse")
    public void addQueryParameter(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "queryParameter", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String queryParameter)
        throws IWebmasterApiAddQueryParameterApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param reason
     * @param siteUrl
     * @param url
     * @throws IWebmasterApiAddPagePreviewBlockApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddPagePreviewBlock", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/AddPagePreviewBlock")
    @RequestWrapper(localName = "AddPagePreviewBlock", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddPagePreviewBlock")
    @ResponseWrapper(localName = "AddPagePreviewBlockResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddPagePreviewBlockResponse")
    public void addPagePreviewBlock(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "url", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String url,
        @WebParam(name = "reason", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        BlockReason reason)
        throws IWebmasterApiAddPagePreviewBlockApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @throws IWebmasterApiAddSiteApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddSite", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/AddSite")
    @RequestWrapper(localName = "AddSite", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddSite")
    @ResponseWrapper(localName = "AddSiteResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddSiteResponse")
    public void addSite(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiAddSiteApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param masterUrl
     * @throws IWebmasterApiAddConnectedPageApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddConnectedPage", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/AddConnectedPage")
    @RequestWrapper(localName = "AddConnectedPage", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddConnectedPage")
    @ResponseWrapper(localName = "AddConnectedPageResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddConnectedPageResponse")
    public void addConnectedPage(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "masterUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String masterUrl)
        throws IWebmasterApiAddConnectedPageApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param delegatedUrl
     * @param siteUrl
     * @param isReadOnly
     * @param authenticationCode
     * @param userEmail
     * @param isAdministrator
     * @throws IWebmasterApiAddSiteRolesApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddSiteRoles", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/AddSiteRoles")
    @RequestWrapper(localName = "AddSiteRoles", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddSiteRoles")
    @ResponseWrapper(localName = "AddSiteRolesResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.AddSiteRolesResponse")
    public void addSiteRoles(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "delegatedUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String delegatedUrl,
        @WebParam(name = "userEmail", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String userEmail,
        @WebParam(name = "authenticationCode", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String authenticationCode,
        @WebParam(name = "isAdministrator", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        Boolean isAdministrator,
        @WebParam(name = "isReadOnly", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        Boolean isReadOnly)
        throws IWebmasterApiAddSiteRolesApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param isEnabled
     * @param queryParameter
     * @throws IWebmasterApiEnableDisableQueryParameterApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "EnableDisableQueryParameter", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/EnableDisableQueryParameter")
    @RequestWrapper(localName = "EnableDisableQueryParameter", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.EnableDisableQueryParameter")
    @ResponseWrapper(localName = "EnableDisableQueryParameterResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.EnableDisableQueryParameterResponse")
    public void enableDisableQueryParameter(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "queryParameter", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String queryParameter,
        @WebParam(name = "isEnabled", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        Boolean isEnabled)
        throws IWebmasterApiEnableDisableQueryParameterApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param url
     * @throws IWebmasterApiFetchUrlApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "FetchUrl", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/FetchUrl")
    @RequestWrapper(localName = "FetchUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.FetchUrl")
    @ResponseWrapper(localName = "FetchUrlResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.FetchUrlResponse")
    public void fetchUrl(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "url", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String url)
        throws IWebmasterApiFetchUrlApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfPagePreview
     * @throws IWebmasterApiGetActivePagePreviewBlocksApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetActivePagePreviewBlocks", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetActivePagePreviewBlocks")
    @WebResult(name = "GetActivePagePreviewBlocksResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetActivePagePreviewBlocks", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetActivePagePreviewBlocks")
    @ResponseWrapper(localName = "GetActivePagePreviewBlocksResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetActivePagePreviewBlocksResponse")
    public ArrayOfPagePreview getActivePagePreviewBlocks(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetActivePagePreviewBlocksApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfBlockedUrl
     * @throws IWebmasterApiGetBlockedUrlsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetBlockedUrls", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetBlockedUrls")
    @WebResult(name = "GetBlockedUrlsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetBlockedUrls", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetBlockedUrls")
    @ResponseWrapper(localName = "GetBlockedUrlsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetBlockedUrlsResponse")
    public ArrayOfBlockedUrl getBlockedUrls(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetBlockedUrlsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param filterProperties
     * @param siteUrl
     * @param page
     * @param url
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfUrlInfo
     * @throws IWebmasterApiGetChildrenUrlInfoApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetChildrenUrlInfo", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetChildrenUrlInfo")
    @WebResult(name = "GetChildrenUrlInfoResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetChildrenUrlInfo", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetChildrenUrlInfo")
    @ResponseWrapper(localName = "GetChildrenUrlInfoResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetChildrenUrlInfoResponse")
    public ArrayOfUrlInfo getChildrenUrlInfo(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "url", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String url,
        @WebParam(name = "page", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        Integer page,
        @WebParam(name = "filterProperties", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        FilterProperties filterProperties)
        throws IWebmasterApiGetChildrenUrlInfoApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param page
     * @param url
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfUrlTrafficInfo
     * @throws IWebmasterApiGetChildrenUrlTrafficInfoApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetChildrenUrlTrafficInfo", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetChildrenUrlTrafficInfo")
    @WebResult(name = "GetChildrenUrlTrafficInfoResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetChildrenUrlTrafficInfo", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetChildrenUrlTrafficInfo")
    @ResponseWrapper(localName = "GetChildrenUrlTrafficInfoResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetChildrenUrlTrafficInfoResponse")
    public ArrayOfUrlTrafficInfo getChildrenUrlTrafficInfo(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "url", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String url,
        @WebParam(name = "page", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        Integer page)
        throws IWebmasterApiGetChildrenUrlTrafficInfoApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfConnectedSite
     * @throws IWebmasterApiGetConnectedPagesApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetConnectedPages", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetConnectedPages")
    @WebResult(name = "GetConnectedPagesResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetConnectedPages", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetConnectedPages")
    @ResponseWrapper(localName = "GetConnectedPagesResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetConnectedPagesResponse")
    public ArrayOfConnectedSite getConnectedPages(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetConnectedPagesApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfCountryRegionSettings
     * @throws IWebmasterApiGetCountryRegionSettingsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCountryRegionSettings", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetCountryRegionSettings")
    @WebResult(name = "GetCountryRegionSettingsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetCountryRegionSettings", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetCountryRegionSettings")
    @ResponseWrapper(localName = "GetCountryRegionSettingsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetCountryRegionSettingsResponse")
    public ArrayOfCountryRegionSettings getCountryRegionSettings(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetCountryRegionSettingsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfUrlWithCrawlIssues
     * @throws IWebmasterApiGetCrawlIssuesApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCrawlIssues", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetCrawlIssues")
    @WebResult(name = "GetCrawlIssuesResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetCrawlIssues", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetCrawlIssues")
    @ResponseWrapper(localName = "GetCrawlIssuesResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetCrawlIssuesResponse")
    public ArrayOfUrlWithCrawlIssues getCrawlIssues(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetCrawlIssuesApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.CrawlSettings
     * @throws IWebmasterApiGetCrawlSettingsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCrawlSettings", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetCrawlSettings")
    @WebResult(name = "GetCrawlSettingsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetCrawlSettings", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetCrawlSettings")
    @ResponseWrapper(localName = "GetCrawlSettingsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetCrawlSettingsResponse")
    public CrawlSettings getCrawlSettings(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetCrawlSettingsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfCrawlStats
     * @throws IWebmasterApiGetCrawlStatsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCrawlStats", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetCrawlStats")
    @WebResult(name = "GetCrawlStatsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetCrawlStats", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetCrawlStats")
    @ResponseWrapper(localName = "GetCrawlStatsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetCrawlStatsResponse")
    public ArrayOfCrawlStats getCrawlStats(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetCrawlStatsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param url
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfDeepLink
     * @throws IWebmasterApiGetDeepLinkApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetDeepLink", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetDeepLink")
    @WebResult(name = "GetDeepLinkResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetDeepLink", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetDeepLink")
    @ResponseWrapper(localName = "GetDeepLinkResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetDeepLinkResponse")
    public ArrayOfDeepLink getDeepLink(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "url", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String url)
        throws IWebmasterApiGetDeepLinkApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfDeepLinkAlgoUrl
     * @throws IWebmasterApiGetDeepLinkAlgoUrlsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetDeepLinkAlgoUrls", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetDeepLinkAlgoUrls")
    @WebResult(name = "GetDeepLinkAlgoUrlsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetDeepLinkAlgoUrls", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetDeepLinkAlgoUrls")
    @ResponseWrapper(localName = "GetDeepLinkAlgoUrlsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetDeepLinkAlgoUrlsResponse")
    public ArrayOfDeepLinkAlgoUrl getDeepLinkAlgoUrls(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetDeepLinkAlgoUrlsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfDeepLinkBlock
     * @throws IWebmasterApiGetDeepLinkBlocksApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetDeepLinkBlocks", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetDeepLinkBlocks")
    @WebResult(name = "GetDeepLinkBlocksResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetDeepLinkBlocks", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetDeepLinkBlocks")
    @ResponseWrapper(localName = "GetDeepLinkBlocksResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetDeepLinkBlocksResponse")
    public ArrayOfDeepLinkBlock getDeepLinkBlocks(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetDeepLinkBlocksApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfDisavowedLink
     * @throws IWebmasterApiGetDisavowedLinksApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetDisavowedLinks", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetDisavowedLinks")
    @WebResult(name = "GetDisavowedLinksResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetDisavowedLinks", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetDisavowedLinks")
    @ResponseWrapper(localName = "GetDisavowedLinksResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetDisavowedLinksResponse")
    public ArrayOfDisavowedLink getDisavowedLinks(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetDisavowedLinksApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param feedUrl
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfFeed
     * @throws IWebmasterApiGetFeedDetailsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetFeedDetails", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetFeedDetails")
    @WebResult(name = "GetFeedDetailsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetFeedDetails", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetFeedDetails")
    @ResponseWrapper(localName = "GetFeedDetailsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetFeedDetailsResponse")
    public ArrayOfFeed getFeedDetails(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "feedUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String feedUrl)
        throws IWebmasterApiGetFeedDetailsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfFeed
     * @throws IWebmasterApiGetFeedsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetFeeds", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetFeeds")
    @WebResult(name = "GetFeedsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetFeeds", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetFeeds")
    @ResponseWrapper(localName = "GetFeedsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetFeedsResponse")
    public ArrayOfFeed getFeeds(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetFeedsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param url
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.FetchedUrlDetails
     * @throws IWebmasterApiGetFetchedUrlDetailsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetFetchedUrlDetails", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetFetchedUrlDetails")
    @WebResult(name = "GetFetchedUrlDetailsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetFetchedUrlDetails", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetFetchedUrlDetails")
    @ResponseWrapper(localName = "GetFetchedUrlDetailsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetFetchedUrlDetailsResponse")
    public FetchedUrlDetails getFetchedUrlDetails(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "url", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String url)
        throws IWebmasterApiGetFetchedUrlDetailsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfFetchedUrl
     * @throws IWebmasterApiGetFetchedUrlsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetFetchedUrls", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetFetchedUrls")
    @WebResult(name = "GetFetchedUrlsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetFetchedUrls", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetFetchedUrls")
    @ResponseWrapper(localName = "GetFetchedUrlsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetFetchedUrlsResponse")
    public ArrayOfFetchedUrl getFetchedUrls(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetFetchedUrlsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param q
     * @param country
     * @param endDate
     * @param language
     * @param startDate
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.Keyword
     * @throws IWebmasterApiGetKeywordApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetKeyword", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetKeyword")
    @WebResult(name = "GetKeywordResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetKeyword", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetKeyword")
    @ResponseWrapper(localName = "GetKeywordResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetKeywordResponse")
    public Keyword getKeyword(
        @WebParam(name = "q", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String q,
        @WebParam(name = "country", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String country,
        @WebParam(name = "language", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String language,
        @WebParam(name = "startDate", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        XMLGregorianCalendar endDate)
        throws IWebmasterApiGetKeywordApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param q
     * @param country
     * @param language
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfKeywordStats
     * @throws IWebmasterApiGetKeywordStatsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetKeywordStats", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetKeywordStats")
    @WebResult(name = "GetKeywordStatsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetKeywordStats", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetKeywordStats")
    @ResponseWrapper(localName = "GetKeywordStatsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetKeywordStatsResponse")
    public ArrayOfKeywordStats getKeywordStats(
        @WebParam(name = "q", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String q,
        @WebParam(name = "country", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String country,
        @WebParam(name = "language", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String language)
        throws IWebmasterApiGetKeywordStatsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param page
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.LinkCounts
     * @throws IWebmasterApiGetLinkCountsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetLinkCounts", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetLinkCounts")
    @WebResult(name = "GetLinkCountsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetLinkCounts", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetLinkCounts")
    @ResponseWrapper(localName = "GetLinkCountsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetLinkCountsResponse")
    public LinkCounts getLinkCounts(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "page", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        Short page)
        throws IWebmasterApiGetLinkCountsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param page
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfQueryStats
     * @throws IWebmasterApiGetPageQueryStatsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPageQueryStats", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetPageQueryStats")
    @WebResult(name = "GetPageQueryStatsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetPageQueryStats", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetPageQueryStats")
    @ResponseWrapper(localName = "GetPageQueryStatsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetPageQueryStatsResponse")
    public ArrayOfQueryStats getPageQueryStats(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "page", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String page)
        throws IWebmasterApiGetPageQueryStatsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfQueryStats
     * @throws IWebmasterApiGetPageStatsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPageStats", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetPageStats")
    @WebResult(name = "GetPageStatsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetPageStats", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetPageStats")
    @ResponseWrapper(localName = "GetPageStatsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetPageStatsResponse")
    public ArrayOfQueryStats getPageStats(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetPageStatsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param query
     * @param page
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfDetailedQueryStats
     * @throws IWebmasterApiGetQueryPageDetailStatsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetQueryPageDetailStats", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetQueryPageDetailStats")
    @WebResult(name = "GetQueryPageDetailStatsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetQueryPageDetailStats", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetQueryPageDetailStats")
    @ResponseWrapper(localName = "GetQueryPageDetailStatsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetQueryPageDetailStatsResponse")
    public ArrayOfDetailedQueryStats getQueryPageDetailStats(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "query", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String query,
        @WebParam(name = "page", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String page)
        throws IWebmasterApiGetQueryPageDetailStatsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param query
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfQueryStats
     * @throws IWebmasterApiGetQueryPageStatsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetQueryPageStats", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetQueryPageStats")
    @WebResult(name = "GetQueryPageStatsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetQueryPageStats", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetQueryPageStats")
    @ResponseWrapper(localName = "GetQueryPageStatsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetQueryPageStatsResponse")
    public ArrayOfQueryStats getQueryPageStats(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "query", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String query)
        throws IWebmasterApiGetQueryPageStatsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfQueryParameter
     * @throws IWebmasterApiGetQueryParametersApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetQueryParameters", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetQueryParameters")
    @WebResult(name = "GetQueryParametersResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetQueryParameters", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetQueryParameters")
    @ResponseWrapper(localName = "GetQueryParametersResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetQueryParametersResponse")
    public ArrayOfQueryParameter getQueryParameters(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetQueryParametersApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfQueryStats
     * @throws IWebmasterApiGetQueryStatsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetQueryStats", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetQueryStats")
    @WebResult(name = "GetQueryStatsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetQueryStats", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetQueryStats")
    @ResponseWrapper(localName = "GetQueryStatsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetQueryStatsResponse")
    public ArrayOfQueryStats getQueryStats(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetQueryStatsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param query
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfRankAndTrafficStats
     * @throws IWebmasterApiGetQueryTrafficStatsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetQueryTrafficStats", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetQueryTrafficStats")
    @WebResult(name = "GetQueryTrafficStatsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetQueryTrafficStats", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetQueryTrafficStats")
    @ResponseWrapper(localName = "GetQueryTrafficStatsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetQueryTrafficStatsResponse")
    public ArrayOfRankAndTrafficStats getQueryTrafficStats(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "query", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String query)
        throws IWebmasterApiGetQueryTrafficStatsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfRankAndTrafficStats
     * @throws IWebmasterApiGetRankAndTrafficStatsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetRankAndTrafficStats", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetRankAndTrafficStats")
    @WebResult(name = "GetRankAndTrafficStatsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetRankAndTrafficStats", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetRankAndTrafficStats")
    @ResponseWrapper(localName = "GetRankAndTrafficStatsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetRankAndTrafficStatsResponse")
    public ArrayOfRankAndTrafficStats getRankAndTrafficStats(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetRankAndTrafficStatsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param q
     * @param country
     * @param endDate
     * @param language
     * @param startDate
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfKeyword
     * @throws IWebmasterApiGetRelatedKeywordsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetRelatedKeywords", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetRelatedKeywords")
    @WebResult(name = "GetRelatedKeywordsResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetRelatedKeywords", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetRelatedKeywords")
    @ResponseWrapper(localName = "GetRelatedKeywordsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetRelatedKeywordsResponse")
    public ArrayOfKeyword getRelatedKeywords(
        @WebParam(name = "q", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String q,
        @WebParam(name = "country", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String country,
        @WebParam(name = "language", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String language,
        @WebParam(name = "startDate", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        XMLGregorianCalendar endDate)
        throws IWebmasterApiGetRelatedKeywordsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfSiteMoveSettings
     * @throws IWebmasterApiGetSiteMovesApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSiteMoves", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetSiteMoves")
    @WebResult(name = "GetSiteMovesResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetSiteMoves", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetSiteMoves")
    @ResponseWrapper(localName = "GetSiteMovesResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetSiteMovesResponse")
    public ArrayOfSiteMoveSettings getSiteMoves(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetSiteMovesApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param includeAllSubdomains
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfSiteRoles
     * @throws IWebmasterApiGetSiteRolesApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSiteRoles", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetSiteRoles")
    @WebResult(name = "GetSiteRolesResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetSiteRoles", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetSiteRoles")
    @ResponseWrapper(localName = "GetSiteRolesResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetSiteRolesResponse")
    public ArrayOfSiteRoles getSiteRoles(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "includeAllSubdomains", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        Boolean includeAllSubdomains)
        throws IWebmasterApiGetSiteRolesApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param url
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.UrlInfo
     * @throws IWebmasterApiGetUrlInfoApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetUrlInfo", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetUrlInfo")
    @WebResult(name = "GetUrlInfoResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetUrlInfo", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetUrlInfo")
    @ResponseWrapper(localName = "GetUrlInfoResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetUrlInfoResponse")
    public UrlInfo getUrlInfo(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "url", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String url)
        throws IWebmasterApiGetUrlInfoApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param link
     * @param page
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.LinkDetails
     * @throws IWebmasterApiGetUrlLinksApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetUrlLinks", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetUrlLinks")
    @WebResult(name = "GetUrlLinksResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetUrlLinks", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetUrlLinks")
    @ResponseWrapper(localName = "GetUrlLinksResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetUrlLinksResponse")
    public LinkDetails getUrlLinks(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "link", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String link,
        @WebParam(name = "page", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        Short page)
        throws IWebmasterApiGetUrlLinksApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.UrlSubmissionQuota
     * @throws IWebmasterApiGetUrlSubmissionQuotaApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetUrlSubmissionQuota", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetUrlSubmissionQuota")
    @WebResult(name = "GetUrlSubmissionQuotaResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetUrlSubmissionQuota", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetUrlSubmissionQuota")
    @ResponseWrapper(localName = "GetUrlSubmissionQuotaResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetUrlSubmissionQuotaResponse")
    public UrlSubmissionQuota getUrlSubmissionQuota(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiGetUrlSubmissionQuotaApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param url
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.UrlTrafficInfo
     * @throws IWebmasterApiGetUrlTrafficInfoApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetUrlTrafficInfo", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetUrlTrafficInfo")
    @WebResult(name = "GetUrlTrafficInfoResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetUrlTrafficInfo", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetUrlTrafficInfo")
    @ResponseWrapper(localName = "GetUrlTrafficInfoResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetUrlTrafficInfoResponse")
    public UrlTrafficInfo getUrlTrafficInfo(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "url", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String url)
        throws IWebmasterApiGetUrlTrafficInfoApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns fogetti.phish.storm.wsdl.bing.webmaster.ArrayOfSite
     * @throws IWebmasterApiGetUserSitesApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetUserSites", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/GetUserSites")
    @WebResult(name = "GetUserSitesResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "GetUserSites", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetUserSites")
    @ResponseWrapper(localName = "GetUserSitesResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.GetUserSitesResponse")
    public ArrayOfSite getUserSites()
        throws IWebmasterApiGetUserSitesApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param blockedUrl
     * @throws IWebmasterApiRemoveBlockedUrlApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveBlockedUrl", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/RemoveBlockedUrl")
    @RequestWrapper(localName = "RemoveBlockedUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveBlockedUrl")
    @ResponseWrapper(localName = "RemoveBlockedUrlResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveBlockedUrlResponse")
    public void removeBlockedUrl(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "blockedUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        BlockedUrl blockedUrl)
        throws IWebmasterApiRemoveBlockedUrlApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param settings
     * @param siteUrl
     * @throws IWebmasterApiRemoveCountryRegionSettingsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveCountryRegionSettings", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/RemoveCountryRegionSettings")
    @RequestWrapper(localName = "RemoveCountryRegionSettings", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveCountryRegionSettings")
    @ResponseWrapper(localName = "RemoveCountryRegionSettingsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveCountryRegionSettingsResponse")
    public void removeCountryRegionSettings(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "settings", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        CountryRegionSettings settings)
        throws IWebmasterApiRemoveCountryRegionSettingsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param market
     * @param deepLinkUrl
     * @param siteUrl
     * @param searchUrl
     * @throws IWebmasterApiRemoveDeepLinkBlockApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveDeepLinkBlock", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/RemoveDeepLinkBlock")
    @RequestWrapper(localName = "RemoveDeepLinkBlock", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveDeepLinkBlock")
    @ResponseWrapper(localName = "RemoveDeepLinkBlockResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveDeepLinkBlockResponse")
    public void removeDeepLinkBlock(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "market", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String market,
        @WebParam(name = "searchUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String searchUrl,
        @WebParam(name = "deepLinkUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String deepLinkUrl)
        throws IWebmasterApiRemoveDeepLinkBlockApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param urlsToProcess
     * @param entitiesToProcess
     * @throws IWebmasterApiRemoveDisavowLinkApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveDisavowLink", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/RemoveDisavowLink")
    @RequestWrapper(localName = "RemoveDisavowLink", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveDisavowLink")
    @ResponseWrapper(localName = "RemoveDisavowLinkResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveDisavowLinkResponse")
    public void removeDisavowLink(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "urlsToProcess", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String urlsToProcess,
        @WebParam(name = "entitiesToProcess", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        Integer entitiesToProcess)
        throws IWebmasterApiRemoveDisavowLinkApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param feedUrl
     * @param siteUrl
     * @throws IWebmasterApiRemoveFeedApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveFeed", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/RemoveFeed")
    @RequestWrapper(localName = "RemoveFeed", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveFeed")
    @ResponseWrapper(localName = "RemoveFeedResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveFeedResponse")
    public void removeFeed(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "feedUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String feedUrl)
        throws IWebmasterApiRemoveFeedApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param url
     * @throws IWebmasterApiRemovePagePreviewBlockApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemovePagePreviewBlock", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/RemovePagePreviewBlock")
    @RequestWrapper(localName = "RemovePagePreviewBlock", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemovePagePreviewBlock")
    @ResponseWrapper(localName = "RemovePagePreviewBlockResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemovePagePreviewBlockResponse")
    public void removePagePreviewBlock(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "url", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String url)
        throws IWebmasterApiRemovePagePreviewBlockApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param queryParameter
     * @throws IWebmasterApiRemoveQueryParameterApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveQueryParameter", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/RemoveQueryParameter")
    @RequestWrapper(localName = "RemoveQueryParameter", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveQueryParameter")
    @ResponseWrapper(localName = "RemoveQueryParameterResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveQueryParameterResponse")
    public void removeQueryParameter(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "queryParameter", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String queryParameter)
        throws IWebmasterApiRemoveQueryParameterApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @throws IWebmasterApiRemoveSiteApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveSite", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/RemoveSite")
    @RequestWrapper(localName = "RemoveSite", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveSite")
    @ResponseWrapper(localName = "RemoveSiteResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveSiteResponse")
    public void removeSite(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiRemoveSiteApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteRole
     * @param siteUrl
     * @throws IWebmasterApiRemoveSiteRoleApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveSiteRole", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/RemoveSiteRole")
    @RequestWrapper(localName = "RemoveSiteRole", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveSiteRole")
    @ResponseWrapper(localName = "RemoveSiteRoleResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.RemoveSiteRoleResponse")
    public void removeSiteRole(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "siteRole", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        SiteRoles siteRole)
        throws IWebmasterApiRemoveSiteRoleApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param crawlSettings
     * @throws IWebmasterApiSaveCrawlSettingsApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SaveCrawlSettings", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/SaveCrawlSettings")
    @RequestWrapper(localName = "SaveCrawlSettings", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.SaveCrawlSettings")
    @ResponseWrapper(localName = "SaveCrawlSettingsResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.SaveCrawlSettingsResponse")
    public void saveCrawlSettings(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "crawlSettings", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        CrawlSettings crawlSettings)
        throws IWebmasterApiSaveCrawlSettingsApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param feedUrl
     * @param siteUrl
     * @throws IWebmasterApiSubmitFeedApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SubmitFeed", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/SubmitFeed")
    @RequestWrapper(localName = "SubmitFeed", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.SubmitFeed")
    @ResponseWrapper(localName = "SubmitFeedResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.SubmitFeedResponse")
    public void submitFeed(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "feedUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String feedUrl)
        throws IWebmasterApiSubmitFeedApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param settings
     * @param siteUrl
     * @throws IWebmasterApiSubmitSiteMoveApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SubmitSiteMove", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/SubmitSiteMove")
    @RequestWrapper(localName = "SubmitSiteMove", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.SubmitSiteMove")
    @ResponseWrapper(localName = "SubmitSiteMoveResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.SubmitSiteMoveResponse")
    public void submitSiteMove(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "settings", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        SiteMoveSettings settings)
        throws IWebmasterApiSubmitSiteMoveApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param url
     * @throws IWebmasterApiSubmitUrlApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SubmitUrl", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/SubmitUrl")
    @RequestWrapper(localName = "SubmitUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.SubmitUrl")
    @ResponseWrapper(localName = "SubmitUrlResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.SubmitUrlResponse")
    public void submitUrl(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "url", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String url)
        throws IWebmasterApiSubmitUrlApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @param deepLink
     * @param weight
     * @param algoUrl
     * @throws IWebmasterApiUpdateDeepLinkApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateDeepLink", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/UpdateDeepLink")
    @RequestWrapper(localName = "UpdateDeepLink", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.UpdateDeepLink")
    @ResponseWrapper(localName = "UpdateDeepLinkResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.UpdateDeepLinkResponse")
    public void updateDeepLink(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl,
        @WebParam(name = "algoUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String algoUrl,
        @WebParam(name = "deepLink", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String deepLink,
        @WebParam(name = "weight", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        DeepLinkDeepLinkWeight weight)
        throws IWebmasterApiUpdateDeepLinkApiFaultFaultFaultMessage
    ;

    /**
     * 
     * @param siteUrl
     * @return
     *     returns java.lang.Boolean
     * @throws IWebmasterApiVerifySiteApiFaultFaultFaultMessage
     */
    @WebMethod(operationName = "VerifySite", action = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api/IWebmasterApi/VerifySite")
    @WebResult(name = "VerifySiteResult", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
    @RequestWrapper(localName = "VerifySite", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.VerifySite")
    @ResponseWrapper(localName = "VerifySiteResponse", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api", className = "fogetti.phish.storm.wsdl.bing.webmaster.VerifySiteResponse")
    public Boolean verifySite(
        @WebParam(name = "siteUrl", targetNamespace = "http://schemas.datacontract.org/2004/07/Microsoft.Bing.Webmaster.Api")
        String siteUrl)
        throws IWebmasterApiVerifySiteApiFaultFaultFaultMessage
    ;

}
